### ISSUE TITLE
inconsistency when changing step_size

### ISSUE THREAD

**Issue by Ch-rode** [grimmlab/ProLaTherm#2] opened 2024-05-14 13:34 UTC
Hello! I was applying your ProLaTherm method to your dummy data, but I noticed that if i change the step_size from the default 10 to (i.e.) 2 in run_prolatherm.py, the scores and so the results are not the same. The step_size/batch size should not influence the scores. 

```
    # Run prediction pipeline in batches of size 10
    start = 0
    step_size = 10
    num_samples = len(sequences)
    preds = []
    scores = []
```

Results with default step_size 10:
```
                      IDs  ...     score
0     sp|Q49610|FTR_METKA  ...  0.242193
1   sp|Q8TWU6|CDAT8_METKA  ...  0.999998
2     sp|Q8TXY4|MER_METKA  ...  0.995104
3    sp|Q9UXR8|HEM1_METKA  ...  1.000000
4     sp|P94951|MTD_METKA  ...  0.990293
5     sp|P94954|MCH_METKA  ...  0.917457
6     sp|Q02394|HMD_METKA  ...  0.902415
7    sp|Q8TUS2|RTCB_METKA  ...  1.000000
8    sp|Q49605|MCRA_METKA  ...  0.962516
9    sp|Q49611|FWDG_METKA  ...  0.813099
10   sp|Q8TVD2|SYS2_METKA  ...  1.000000
11   sp|Q8TX89|MPTD_METKA  ...  0.893427
12    sp|Q8TXU4|FEN_METKA  ...  1.000000
13   sp|Q8TXW1|AMZA_METKA  ...  1.000000
14  sp|Q8TGZ5|ENDAL_METKA  ...  1.000000
```

Results with step_size 2:
```
                      IDs  ...     score
0     sp|Q49610|FTR_METKA  ...  0.752126
1   sp|Q8TWU6|CDAT8_METKA  ...  1.000000
2     sp|Q8TXY4|MER_METKA  ...  0.999996
3    sp|Q9UXR8|HEM1_METKA  ...  1.000000
4     sp|P94951|MTD_METKA  ...  1.000000
5     sp|P94954|MCH_METKA  ...  0.999993
6     sp|Q02394|HMD_METKA  ...  0.902414
7    sp|Q8TUS2|RTCB_METKA  ...  1.000000
8    sp|Q49605|MCRA_METKA  ...  0.999493
9    sp|Q49611|FWDG_METKA  ...  0.985330
10   sp|Q8TVD2|SYS2_METKA  ...  1.000000
11   sp|Q8TX89|MPTD_METKA  ...  0.893427
12    sp|Q8TXU4|FEN_METKA  ...  1.000000
13   sp|Q8TXW1|AMZA_METKA  ...  1.000000
14  sp|Q8TGZ5|ENDAL_METKA  ...  0.062475
```

**Comment by Eloi12** [comment] 2024-06-04 08:25
Yes I agree I have the very same remark

**Comment by fhaselbeck** [comment] 2024-06-04 10:02
Dear Users,

Sorry for the late reply. Due to several circumstances, we did not have time to review the issue already. We blocked some time to do it next week and will let you know.

Sorry for the inconvenience.

Kind regards

**Comment by fhaselbeck** [comment] 2024-06-13 15:33
Dear User,

first of all: sorry for the delay and thanks you very much for reporting the issue.
We had indeed a bug in the inference code of ProLaTherm, which we fixed now. So now the results are consistent and not depending on the step size as intended.

Hope our prediction model is useful for your research!

Thanks and kind regards,
Florian

**Closed as completed by fhaselbeck** 2024-06-13 15:33 UTC
