### ISSUE TITLE
Prediction depends on step size ?

### ISSUE THREAD

**Issue by Eloi12** [grimmlab/ProLaTherm#3] opened 2024-06-04 08:24 UTC
Hello, I tested your model but the prediction seems to change with the "step_size" parameter. This is the simplest way I've tested to avoid CUDA memory overload. Do you have any idea why the results change with the "step_size" value? If I keep this parameter at 10, how can I avoid memory overload?
Have a nice day!

**Comment by fhaselbeck** [comment] 2024-06-04 10:02
Dear Eloi12, 

Sorry for the late reply. Due to several circumstances, we did not have time to review the issue already. We blocked some time to do it next week and will let you know.

Sorry for the inconvenience.

Kind regards

**Comment by fhaselbeck** [comment] 2024-06-13 15:34
Dear User,

first of all: sorry for the delay and thanks you very much for reporting the issue.
We had indeed a bug in the inference code of ProLaTherm, which we fixed now. So now the results are consistent and not depending on the step size as intended.

Hope our prediction model is useful for your research!

Thanks and kind regards,
Florian

**Closed as completed by fhaselbeck** 2024-06-13 15:34 UTC
